### ISSUE TITLE
React 18

### ISSUE THREAD

**Issue by 0Serenvale** [dane-brown/react-sanity-pagination#12]
Hi

Is is possible to upgrade it to react 18 ?
Or is there a work around it

Thank you
Regards.

**Comment by Nadir-Enthusiast** [comment]
`npm i react` automatically should install the latest version or update the existing one

**Comment by 0Serenvale** [comment]
@Nadir-Enthusiast 
Well Nadir I'm talking about the plugin, not react itself.

**Comment by Nadir-Enthusiast** [comment]
oh, I didn't notice the title, sorry.
According to the npm's official website the latest version of react-sanity-pagination was released 3 years ago. For more info: https://www.npmjs.com/package/react-sanity-pagination . 
And as you can guess react 18 was released far later than that.

**Comment by dane-brown** [comment]
Hi, I don't actively maintain this plugin anymore although I'm open to PR's if you'd like to get it up to date.
